[platformio]
extra_configs = platformio_local.ini

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:usb]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = 192.168.0.27