[platformio]
extra_configs = platformio_local.ini

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.psram_type = opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:usb]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = 192.168.0.27